### ISSUE TITLE
Custom informations

### ISSUE THREAD

**Issue by eoli3n** [Macchina-CLI/macchina#105]
I would like to be able to wrap some custom commands to display information I chose.
Like 
```
# Show available upgrade in Voidlinux
custom_info:
  - name: XBPS
    command: xbps-query -Mnu | wc -l
```
I would use your fetcher on remote hosts, and run it at each login to get some useful informations, and display it prettily.
