### ISSUE TITLE
ascii art positioning

### ISSUE THREAD

**Issue by hertg** [Macchina-CLI/macchina#183]
I've glanced over the theme documentation and I don't think there's this possibility yet.

Add a setting to specify the position where the ascii art should be displayed. Currently, it always displays on the left.
I have a fairly wide but short ascii art I'd like to use, it would look best if it was above the system info box.
Having a wide ascii art side by side with the system info doesn't work well in narrow terminal windows.

Something like:

```toml
[custom_ascii]
# Possible values: top, right, bottom, left
# Default value: left
position = "top"
```

**Comment by grtcdr** [comment]
This is interesting, we could definitely do this :)

**Comment by hertg** [comment]
Just had an afterthought about that feature-request, so I'll just leave that here as a brain-dump, it may be a bit overkill (?)

Additionally to the positioning, specifying the alignment could also be pretty cool. Alignment could for example be an enum of: `Start`, `Center`, or `End`.

```toml
[custom_ascii]
# Possible values: start, center, end
# Default value: start
alignment = "center"
```

Example for what I mean:
```
       alignment: start                alignment: center               alignment: end
  _______  __________________              __________________              __________________
  |     |  |                |              |                |              |                |
  | img |  |                |     _______  |                |              |                |
  |_____|  |                |     |     |  |                |              |                |
           |      text      |     | img |  |      text      |     _______  |      text      |
           |                |     |_____|  |                |     |     |  |                |
           |                |              |                |     | img |  |                |
           |________________|              |________________|     |_____|  |________________|
```

If the textbox is larger than the ascii image, then the alignment could be applied to the box instead.
