### ISSUE TITLE
[BUG] 'custom_ascii.color' config should be optional

### ISSUE THREAD

**Issue by hertg** [Macchina-CLI/macchina#188]
**Describe the bug**
If I configure a custom ascii art but don't configure the `color` key, macchina doesn't load the theme and instead shows an error message:
```
Warning: Invalid theme "<theme name>", falling back to default.
Suggestion: Perhaps the theme doesn't exist?
```

**To Reproduce**
Create a theme with a custom ascii art, but the color config omitted.
```toml
[custom_ascii]
#color = "Yellow"
path = "/home/michael/.config/macchina/arch.ascii"
```

**Expected behavior**
Macchina should render the custom ascii art as is, without re-coloring it.
My ascii art has multiple colors, specifying the `color` config would paint it all in just one color.
